/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.app.poker.game.ui;

import com.app.poker.game.Carta;
import com.app.poker.game.Dealer;
import com.app.poker.game.Mesa;
import com.app.poker.game.Player;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Sail3
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    Dealer dealer = new Dealer(1);
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPlayer = new javax.swing.JPanel();
        jBJugar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPMano = new javax.swing.JPanel();
        cartaMano01 = new javax.swing.JLabel();
        cartaMano02 = new javax.swing.JLabel();
        jPMesa = new javax.swing.JPanel();
        cartaMesa01 = new javax.swing.JLabel();
        cartaMesa02 = new javax.swing.JLabel();
        cartaMesa03 = new javax.swing.JLabel();
        cartaMesa04 = new javax.swing.JLabel();
        cartaMesa05 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPlayer.setBackground(new java.awt.Color(50, 130, 45));

        jBJugar.setFont(new java.awt.Font("Agency FB", 2, 36)); // NOI18N
        jBJugar.setText("Iniciar");
        jBJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBJugarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Agency FB", 2, 36)); // NOI18N
        jButton1.setText("Fold");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPMano.setBackground(new java.awt.Color(50, 130, 45));

        cartaMano01.setBackground(new java.awt.Color(24, 145, 40));
        cartaMano01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg"))); // NOI18N
        cartaMano01.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        cartaMano02.setBackground(new java.awt.Color(24, 145, 40));
        cartaMano02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg"))); // NOI18N
        cartaMano02.setText("jLabel1");
        cartaMano02.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.GroupLayout jPManoLayout = new javax.swing.GroupLayout(jPMano);
        jPMano.setLayout(jPManoLayout);
        jPManoLayout.setHorizontalGroup(
            jPManoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPManoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cartaMano01, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cartaMano02, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPManoLayout.setVerticalGroup(
            jPManoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPManoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPManoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cartaMano01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cartaMano02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPlayerLayout = new javax.swing.GroupLayout(jPlayer);
        jPlayer.setLayout(jPlayerLayout);
        jPlayerLayout.setHorizontalGroup(
            jPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPMano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                .addGroup(jPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBJugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPlayerLayout.setVerticalGroup(
            jPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPMano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPlayerLayout.createSequentialGroup()
                        .addComponent(jBJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPlayer, java.awt.BorderLayout.NORTH);

        jPMesa.setBackground(new java.awt.Color(50, 130, 45));

        cartaMesa01.setBackground(new java.awt.Color(24, 145, 40));
        cartaMesa01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg"))); // NOI18N
        cartaMesa01.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        cartaMesa02.setBackground(new java.awt.Color(24, 145, 40));
        cartaMesa02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg"))); // NOI18N
        cartaMesa02.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        cartaMesa03.setBackground(new java.awt.Color(24, 145, 40));
        cartaMesa03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg"))); // NOI18N
        cartaMesa03.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        cartaMesa04.setBackground(new java.awt.Color(24, 145, 40));
        cartaMesa04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg"))); // NOI18N
        cartaMesa04.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        cartaMesa05.setBackground(new java.awt.Color(24, 145, 40));
        cartaMesa05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg"))); // NOI18N
        cartaMesa05.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.GroupLayout jPMesaLayout = new javax.swing.GroupLayout(jPMesa);
        jPMesa.setLayout(jPMesaLayout);
        jPMesaLayout.setHorizontalGroup(
            jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cartaMesa01)
                .addGap(18, 18, 18)
                .addComponent(cartaMesa02)
                .addGap(18, 18, 18)
                .addComponent(cartaMesa03)
                .addGap(18, 18, 18)
                .addComponent(cartaMesa04)
                .addGap(18, 18, 18)
                .addComponent(cartaMesa05)
                .addContainerGap())
        );
        jPMesaLayout.setVerticalGroup(
            jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cartaMesa05)
                    .addComponent(cartaMesa02)
                    .addComponent(cartaMesa01)
                    .addComponent(cartaMesa03)
                    .addComponent(cartaMesa04))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPMesa, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBJugarActionPerformed
        jBJugar.setText("Continuar");
        dealer.repartir();
        repartirCartas();
    }//GEN-LAST:event_jBJugarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*Limpiamos al dealer*/
        dealer.limpiar();
        /*Inicializamos las cartas de la mesa*/
        cartaMesa01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg")));
        cartaMesa02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg")));
        cartaMesa03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg")));
        cartaMesa04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg")));
        cartaMesa05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg")));
        
        /*Inicializamos los las cartas de la mano*/
        cartaMano01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg")));
        cartaMano02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/poker/game/ui/cards/Baraja.jpg")));
    }//GEN-LAST:event_jButton1ActionPerformed
    private void repartirCartas(){
        Carta[] cartas = dealer.getMesa().getCartas();
        for (int i = 0; i < cartas.length; i++) {
            Carta card = cartas[i];
            if (card != null) {
                repartirMesa(card, (i + 1));
            }
        }
        ArrayList<Player> jugadores = dealer.getJugadores();
        Iterator it = jugadores.iterator();
        while (it.hasNext()) {
            Player jugador = (Player) it.next();
            cartas = jugador.getCartas();
            for (int i = 0; i < cartas.length; i++) {
                Carta card = cartas[i];
                if (card != null) {
                    repartirMano(card, (i + 1));
                }
            }
        }
    }
    private void repartirMano(Carta carta, int indice) {
        String ruta = "/com/app/poker/game/ui/cards/" + carta.getPalo() + "/" + carta.getNombre() + ".jpg";
        switch (indice) {
            case 1:
                cartaMano01.setIcon(new ImageIcon(getClass().getResource(ruta)));
                break;
            case 2:
                cartaMano02.setIcon(new ImageIcon(getClass().getResource(ruta)));
                break;
            default:
                throw new AssertionError();
        }
    }
    private void repartirMesa(Carta carta, int indice){
        String ruta = "/com/app/poker/game/ui/cards/" + carta.getPalo() + "/" + carta.getNombre() + ".jpg";
        switch (indice) {
            case 1:
                cartaMesa01.setIcon(new ImageIcon(getClass().getResource(ruta)));
                break;
            case 2:
                cartaMesa02.setIcon(new ImageIcon(getClass().getResource(ruta)));
                break;
            case 3:
                cartaMesa03.setIcon(new ImageIcon(getClass().getResource(ruta)));
                break;
            case 4:
                cartaMesa04.setIcon(new ImageIcon(getClass().getResource(ruta)));
                break;
            case 5:
                cartaMesa05.setIcon(new ImageIcon(getClass().getResource(ruta)));
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartaMano01;
    private javax.swing.JLabel cartaMano02;
    private javax.swing.JLabel cartaMesa01;
    private javax.swing.JLabel cartaMesa02;
    private javax.swing.JLabel cartaMesa03;
    private javax.swing.JLabel cartaMesa04;
    private javax.swing.JLabel cartaMesa05;
    private javax.swing.JButton jBJugar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPMano;
    private javax.swing.JPanel jPMesa;
    private javax.swing.JPanel jPlayer;
    // End of variables declaration//GEN-END:variables
}
